services:
  server:
    restart: always
    #    depends_on:
    #      - db
    image: node:22-alpine
    build:
      dockerfile: api/server/dev.Dockerfile
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    env_file:
      - ./api/server/.env

    volumes:
      - .:/app
